version: '3.8'

services:
  # API Service
  api:
    image: ghcr.io/zapagenrevdale/api:latest
    container_name: api
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "4000:4000"
    networks:
      - app-network
    restart: unless-stopped

  # Documentation Service (Next.js)
  doc:
    image: ghcr.io/zapagenrevdale/doc:latest
    container_name: doc
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost/api
    ports:
      - "3000:3000"
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - api

  # App Service (Vite React)
  app:
    image: ghcr.io/zapagenrevdale/app:latest
    container_name: app
    environment:
      - VITE_API_URL=http://localhost/api
    ports:
      - "3001:3001"
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - api

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - api
      - doc
      - app

networks:
  app-network:
    driver: bridge
