name: Dev Deployment

on:
  push:
    branches:
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  infra-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 10.10.0

      - name: Setup Node 22
        uses: actions/setup-node@v4
        with:
          node-version: v22.14.0
          cache: "pnpm"

      - name: Install deps
        run: pnpm install

      - name: Preview Deploy
        env: DATABASE_URL=${{ secrets.DATABASE_URL }}
        run: |
          cd infra
          export DATABASE_URL=$DATABASE_URL
          pnpm sst deploy --stage dev
