name: Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches-ignore:
      - dev
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  infra-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 10.10.0

      - name: Setup Node 22
        uses: actions/setup-node@v4
        with:
          node-version: v22.14.0
          cache: "pnpm"

      - name: Install deps
        run: pnpm install

      - name: Preview Deploy
        run: |
          cd infra
          export COMMIT_SHA=${GITHUB_SHA::7}
          pnpm sst deploy --stage dev
