name: Parallel GHCR Image Builds

on:
  push:
    branches: [main]

jobs:
  app:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push app image
        run: |
          docker build -f dockers/Dockerfile.app -t ghcr.io/${{ github.actor }}/app:latest .
          docker push ghcr.io/${{ github.actor }}/app:latest

  api:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push api image
        run: |
          docker build -f dockers/Dockerfile.api -t ghcr.io/${{ github.actor }}/api:latest .
          docker push ghcr.io/${{ github.actor }}/api:latest

  doc:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push doc image
        run: |
          docker build -f dockers/Dockerfile.doc -t ghcr.io/${{ github.actor }}/doc:latest .
          docker push ghcr.io/${{ github.actor }}/doc:latest
